Repository EIP-SunChaser/SunChaser, pull requests merged in 2024-10, with the labels that each got.

#52 Main menu loading screen
  Scenes/Menus/main_menu.tscn
  Scripts/Menus/main_menu.gd
  Scripts/Menus/tips.gd
Labels: feature

#55 Feat/make the options menu controller compatible
  Scenes/Menus/general_settings.tscn
  Scenes/Menus/input_button.tscn
  Scenes/Menus/input_settings.tscn
  Scenes/Menus/options_menu.tscn
  Scenes/Menus/settings_tab_container.tscn
  Scripts/Entities/player.gd
  Scripts/Menus/general_settings.gd
  Scripts/Menus/input_settings.gd
  Scripts/Menus/options_menu.gd
  project.godot
Labels: feature

#65 Bug/exit main menu #24 #25
  Scripts/Menus/pause_menu.gd
Labels: bug, feature

#68 Feat/graphics settings
  Scenes/Menus/audio_settings.tscn
  Scenes/Menus/options_menu.tscn
  Scenes/Menus/settings_tab_container.tscn
  Scenes/Menus/video_settings.tscn
  Scripts/Autoload/config_file_handler.gd
  Scripts/Menus/audio_settings.gd
  Scripts/Menus/options_menu.gd
  Scripts/Menus/video_settings.gd
Labels: feature

#67 [ADD] All wheels can now be destroyed
  Scenes/Entities/jolt_car.tscn
  Scenes/Items/wheel.tscn
  Scripts/Entities/BodyPart.gd
  Scripts/Entities/jolt_car.gd
  Scripts/Entities/wheel.gd
  Scripts/Menus/main_menu.gd
Labels: feature

#69 [FIX] Reset main menu to fix loading screen
  Scripts/Menus/main_menu.gd
  Scripts/Menus/pause_menu.gd
Labels: bug
